import React from "react";
import { Button, Spinner, Image } from "react-bootstrap";
import { FaCheckCircle, FaCircle, FaEllipsisH } from "react-icons/fa";
import useUserMedia from "../../hooks/useUserMedia";

function NotificationItem({ notification, handleMarkRead, handleMarkUnread }) {
  const { mediaUrl, loading: mediaLoading } = useUserMedia(
    notification.userId,
    "PROFILE",
    "image"
  );

  const renderImage = () => {
    if (mediaLoading) {
      return <Spinner animation="border" size="sm" className="me-2 mt-1" />;
    }
    return (
      <Image
        src={mediaUrl || "https://placehold.co/40x40?text=Avatar"}
        roundedCircle
        className="me-2"
        style={{ width: "40px", height: "40px", objectFit: "cover" }}
        alt={`Avatar của ${notification.user}`}
      />
    );
  };

  return (
    <div
      className={`p-3 border-bottom ${
        !notification.isRead ? "bg-light-primary" : "opacity-75"
      }`}
    >
      <div className="d-flex align-items-start">
        {renderImage()}
        <div className="flex-grow-1">
          <div className="d-flex justify-content-between align-items-center">
            <p
              className="fw-bold mb-0 cursor-pointer text-primary"
              onClick={() =>
                handleMarkRead(notification.id, notification.username)
              }
            >
              {notification.user}
            </p>
            <div>
              {!notification.isRead ? (
                <Button
                  variant="link"
                  className="text-dark p-0 me-2"
                  onClick={() => handleMarkRead(notification.id)}
                >
                  <FaCheckCircle />
                </Button>
              ) : (
                <Button
                  variant="link"
                  className="text-dark p-0 me-2"
                  onClick={() => handleMarkUnread(notification.id)}
                >
                  <FaCircle />
                </Button>
              )}
              <Button variant="link" className="text-dark p-0">
                <FaEllipsisH />
              </Button>
            </div>
          </div>

          <p className="mb-1">{notification.content}</p>

          {notification.tags?.length > 0 && (
            <p className="text-primary small mb-1">
              {notification.tags.map((tag, index) => (
                <span key={index} className="me-1">
                  {tag}
                </span>
              ))}
            </p>
          )}

          {notification.image?.startsWith("http") && (
            <Image
              src={notification.image}
              fluid
              className="mt-2"
              style={{ maxWidth: "100%", height: "auto" }}
            />
          )}

          {notification.image?.startsWith("This image is generated by AI") && (
            <p className="text-muted small mt-2">{notification.image}</p>
          )}

          <p className="text-muted small">{notification.timestamp}</p>
        </div>
      </div>
    </div>
  );
}

export default NotificationItem;
